#!/bin/bash


horizontal (){
    xsetwacom set "Wacom Intuos PT S 2 Pen stylus" rotate none
}

vertical () {
    xsetwacom set "Wacom Intuos PT S 2 Pen stylus" rotate cw
}

die() { echo ">> ERROR: $@" 1>&2 ; exit 1; }
dbg() { echo ">> $@"; }


function usage()
{
    echo "AdjustWacom Intuos PT S 2 Pen stylus orientation"
    echo "usage:"
    echo "  $0"
    echo "    -h --help"
    echo "    horizontal  set orientation to horizontal"
    echo "    vertical set orientation to vertical"
    echo ""
}


if [ $# -ne 1 ];
then
  echo "ERROR: need at least one argument"
  echo ""
  usage
fi


#dbg "parsing parameters"
while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    #dbg "   $PARAM=$VALUE"
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        horizontal)
            horizontal
            ;;
        vertical)
            vertical
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done
